# 202108210133罗毅夫

# NumPy 库
### 核心对象是N维数组
#### ndarry基本概念
轴（axes）：数组维度
秩（rank）：数组的维度（ndim）
数据类型（dtype）
形状（shape）
大小（size）

In [20]:
import numpy as np
bArray = np.array([[1,2,3],[4,5,6]])
print(bArray.ndim)
print(bArray.dtype)
print(bArray.itemsize)
print(bArray.shape)
print(bArray.size)

2
int64
8
(2, 3)
6


In [23]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [24]:
np.zeros((2, 2), dtype=int)

array([[0, 0],
       [0, 0]])

In [30]:
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [31]:
np.linspace(1,2,10,endpoint=False)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [34]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [40]:
a1 = a2 = np.ones((2,3),dtype=int)
print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2) # python除法默认以浮点数输出

[[2 2 2]
 [2 2 2]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [76]:
room = np.array([[[0, 1, 2,3],[4,5,6,7],[8,9,10,11]],[[12,13,14,15],[16,17,18,19],[20,21,22,23]]])
room[0,0,0] #or room[0][0][0]
room[1,0,1]
room[1,0:2,2:4]
room[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
a3 = a1.transpose()
print(a1)
print(a3)

a4 = np.arange(6).reshape((2,3))
a5 = a4.flatten()
print(a4)
print(a5)

[[1 1 1]
 [1 1 1]]
[[1 1]
 [1 1]
 [1 1]]
[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


In [99]:
aa1 = np.arange(6).reshape((2,3))
print(aa1)
aa1.sum()
aa1.sum(axis=0)
aa1.sum(axis=1)


[[0 1 2]
 [3 4 5]]


array([ 3, 12])