# 202108210133 罗毅夫

In [11]:
import numpy as np
a = np.array([[1,1],[2,4]])
b = np.array([35,94])
x = np.linalg.solve(a,b) # linalg.solve： 求线性方程的解

print(np.array(x, dtype=int))
print(a.dot(x)) # dot：点集，矩阵的乘法运算

[23 12]
[35. 94.]


In [22]:
a = np.array([1,-2,0,1])
c = np.poly1d(a) # 生成多项式
print(c)
print(np.polyval(c,2)) # === c(2)
print(np.polyder(c,m=1))
print(np.polyint(c,m=1))
b = np.array([1,1,1,1])
d = np.poly1d(b)
print(np.polyadd(c,d))
print(np.polysub(c,d))

   3     2
1 x - 2 x + 1
1
   2
3 x - 4 x
      4          3
0.25 x - 0.6667 x + 1 x
   3     2
2 x - 1 x + 1 x + 2
    2
-3 x - 1 x


In [31]:
a = np.arange(50).reshape((5,10))
np.savetxt('./file/document.txt',a,fmt='%d') # 写入文件
np.savetxt('./file/document.csv',a,fmt='%d',delimiter=',') #写入为csv（逗号分隔）文件

In [36]:
print(np.loadtxt('./file/document.txt',dtype=int))
print(np.loadtxt('./file/document.csv',dtype=int,delimiter=','))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


NameError: name 'Math' is not defined